spring.application.name=myFirst
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
# ADD THIS LINE BELOW:
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true